stages:
  - build
  - test
  - security
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  DOCKER_DRIVER: overlay2

# Cache configuration
cache:
  paths:
    - .m2/repository
    - frontend/node_modules/

# Build Backend
build:backend:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 hour
  only:
    - develop
    - main

# Build Frontend
build:frontend:
  stage: build
  image: node:18-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour
  only:
    - develop
    - main

# Test Backend
test:backend:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - cd backend
    - mvn test
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit:
        - backend/target/surefire-reports/TEST-*.xml
  only:
    - develop
    - main

# Test Frontend
test:frontend:
  stage: test
  image: node:18-alpine
  script:
    - cd frontend
    - npm ci
    - npm run test -- --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  only:
    - develop
    - main

# Security Scan
security:dependency-check:
  stage: security
  image: maven:3.9-eclipse-temurin-17
  script:
    - cd backend
    - mvn dependency-check:check
  allow_failure: true
  only:
    - develop
    - main

# Deploy to Staging
deploy:staging:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up -d
  environment:
    name: staging
    url: https://staging.elektromeistras.lt
  only:
    - develop

# Deploy to Production
deploy:production:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml up -d
  environment:
    name: production
    url: https://elektromeistras.lt
  when: manual
  only:
    - main
