spring:
  application:
    name: elektromeistras-backend
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:elektromeistras}
    username: ${DB_USERNAME:elektromeistras}
    password: ${DB_PASSWORD:elektromeistras}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60000
    elasticsearch:
      repositories:
        enabled: true
  
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}
  
  security:
    jwt:
      secret: ${JWT_SECRET:elektromeistras-super-secret-key-change-in-production}
      access-token-expiration: 900000 # 15 minutes
      refresh-token-expiration: 604800000 # 7 days

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    lt.elektromeistras: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
